### ISSUE TITLE
Flet build apk not working

### ISSUE THREAD

**Issue by gatsz1** [flet-dev/flet-build-template#9]
This is the error i'm receiving .. I have checked my windows version its upto date including everything else

(.venv) PS C:\Users\Ian\Desktop\flet\.venv\YTDownloader> flet build windows
Creating Flutter bootstrap project from gh:flet-dev/flet-build-template with ref 0.22.1...OK
Customizing app icons and splash images...OK
Generating app icons...Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ian\Desktop\flet\.venv\Scripts\flet.exe\__main__.py", line 7, in <module>
  File "C:\Users\Ian\Desktop\flet\.venv\Lib\site-packages\flet\cli\cli.py", line 88, in main
  File "C:\Users\Ian\Desktop\flet\.venv\Lib\site-packages\flet\cli\commands\build.py", line 848, in run                                                                                613, in handle
    r = subprocess.run(
        ^^^^^^^^^^^^^^^
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548,  848, in run
in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                       in run
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,                            in __init__
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child                                                                          in _execute_child        
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by FeodorFitsner** [comment]
If you have Python 3.12.0 - upgrade it. Also, this is similar/related issue: https://github.com/flet-dev/flet/issues/2318

**Comment by gatsz1** [comment]
Fixed thank you
